### ISSUE TITLE
Figure out why running `get_temp_role` twice on settings page breaks behat tests

### ISSUE THREAD

**Issue by andyzito** [LafColITS/moodle-local_temporary_enrolments#8]
Very weird. If I call `get_temp_role` twice on the settings page, the behat tests throw a ton of "duplicate admin page name" errors. Have been unable to duplicate the error outside of behat. What???

**Comment by azito122** [comment]
For historical purposes, this was a false positive -- the actual problem was a case in which the code ended up trying to get the property of a non-object. Not sure why that threw a "duplicate admin page" error instead of "property of a non-object" error, but whatever.
